# Generated by Django 3.2.5 on 2021-07-25 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_ad_advertiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertiser_management.advertiser'),
        ),
    ]
