# Generated by Django 3.2.5 on 2021-07-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0003_alter_ad_advertiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='img_url',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='ad_pics'),
        ),
    ]
